/* Generated by Yosys 0.31+16 (git sha1 b04d0e09e, gcc 11.3.0-1ubuntu1~22.04.1 -fPIC -Os) */

(* top =  1  *)
(* src = "mux_generate.v:1.1-12.10" *)
module mux_generate(i0, i1, i2, i3, sel, y);
  (* src = "mux_generate.v:5.1-11.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "mux_generate.v:5.1-11.4" *)
  wire _07_;
  wire _08_;
  (* src = "mux_generate.v:1.28-1.30" *)
  wire _09_;
  (* src = "mux_generate.v:1.39-1.41" *)
  wire _10_;
  (* src = "mux_generate.v:1.49-1.51" *)
  wire _11_;
  (* src = "mux_generate.v:1.60-1.62" *)
  wire _12_;
  (* src = "mux_generate.v:1.77-1.80" *)
  wire _13_;
  (* src = "mux_generate.v:1.77-1.80" *)
  wire _14_;
  (* src = "mux_generate.v:1.28-1.30" *)
  input i0;
  wire i0;
  (* src = "mux_generate.v:1.39-1.41" *)
  input i1;
  wire i1;
  (* src = "mux_generate.v:1.49-1.51" *)
  input i2;
  wire i2;
  (* src = "mux_generate.v:1.60-1.62" *)
  input i3;
  wire i3;
  (* src = "mux_generate.v:2.12-2.17" *)
  wire [3:0] i_int;
  (* src = "mux_generate.v:4.9-4.10" *)
  wire [31:0] k;
  (* src = "mux_generate.v:1.77-1.80" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "mux_generate.v:1.95-1.96" *)
  output y;
  reg y;
  sky130_fd_sc_hd__mux4_2 _15_ (
    .A0(_09_),
    .A1(_10_),
    .A2(_11_),
    .A3(_12_),
    .S0(_13_),
    .S1(_14_),
    .X(_07_)
  );
  (* src = "mux_generate.v:5.1-11.4" *)
  always @*
    if (!_01_) y = _00_;
  assign i_int = { i3, i2, i1, i0 };
  assign k = 32'd4;
  assign _08_ = 1'h0;
  assign _14_ = sel[1];
  assign _13_ = sel[0];
  assign _09_ = i0;
  assign _10_ = i1;
  assign _11_ = i2;
  assign _12_ = i3;
  assign _00_ = _07_;
  assign _01_ = _08_;
endmodule
